[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/gist-vim'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rking/ag.vim'
